#!/bin/bash
# Created by knightvps
# Uban User.
red='\e[1;31m'
green='\e[0;32m'
blue='\e[1;34m'
NC='\e[0m'
echo "Connecting to knightvps unlock panel....."
sleep 0.2


read -p "Masukkan Username Yang Ingin Anda Unlock: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
passwd -u $username
clear
  echo " "
  echo "-----------------------------------------------"
  echo -e "Username ${blue}$username${NC} Sudah berhasil di ${green}BUKA KUNCINYA${NC}."
  echo -e "Akses untuk Username ${blue}$username${NC} Sudah Dikembalikan"
  echo "Seperti Sediakala"
  echo "-----------------------------------------------"
else
echo "Username tidak ditemukan di server anda"
    exit 1
fi
